# Generated by Django 3.0.8 on 2020-08-01 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproducts',
            old_name='quantify',
            new_name='quantity',
        ),
    ]
