# Generated by Django 3.0.8 on 2020-08-11 02:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping_addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipping_adress',
            new_name='ShippingAddress',
        ),
    ]
